import { Playlist, Song } from "@/types";

export const mockPlaylist: Playlist = {
  id: "1",
  name: "Coding Music",
  slug: "coding-music",
  description: "Best tracks to code to. Upvote your favorites!",
  owner_id: "user-1",
  spotify_playlist_id: "spotify-playlist-1",
  is_locked: false,
  max_songs_per_user: 3,
  vote_threshold: 20,
  created_at: new Date().toISOString(),
  owner: {
    id: "user-1",
    spotify_id: "spotify-user-1",
    display_name: "DJ Coder",
    created_at: new Date().toISOString(),
  },
};

export const mockSongs: Song[] = [
  {
    id: "s1",
    playlist_id: "1",
    spotify_track_id: "4cOdK2wGLETKBW3PvgPWqT",
    title: "Never Gonna Give You Up",
    artist: "Rick Astley",
    album_cover: "https://i.scdn.co/image/ab67616d0000b27315b2e2b0925faf1e15a5b5c7",
    added_by: "@musiclover",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    upvotes: 42,
    downvotes: 3,
    score: 39,
    status: "approved",
    synced_to_spotify: true,
    user_vote: null,
  },
  {
    id: "s2",
    playlist_id: "1",
    spotify_track_id: "3n3Ppam7vgaVa1iaRUc9Lp",
    title: "Midnight City",
    artist: "M83",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273c3af0c2b92f85985e0e743e7",
    added_by: "@nightowl",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    upvotes: 35,
    downvotes: 5,
    score: 30,
    status: "approved",
    synced_to_spotify: true,
    user_vote: 1,
  },
  {
    id: "s3",
    playlist_id: "1",
    spotify_track_id: "1BxfuPKGuaTgP7aM0Bbdwr",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album_cover: "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
    added_by: "@synthwave",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    upvotes: 28,
    downvotes: 2,
    score: 26,
    status: "approved",
    synced_to_spotify: true,
    user_vote: null,
  },
  {
    id: "s4",
    playlist_id: "1",
    spotify_track_id: "0VjIjW4GlUZAMYd2vXMi3b",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273e8b066f70c206551210d902b",
    added_by: "@classicrock",
    created_at: new Date(Date.now() - 5400000).toISOString(),
    upvotes: 18,
    downvotes: 4,
    score: 14,
    status: "approved",
    synced_to_spotify: false,
    user_vote: -1,
  },
  {
    id: "s5",
    playlist_id: "1",
    spotify_track_id: "7qiZfU4dY1lWllzX7mPBI3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
    added_by: "@popfan",
    created_at: new Date(Date.now() - 9000000).toISOString(),
    upvotes: 12,
    downvotes: 8,
    score: 4,
    status: "pending",
    synced_to_spotify: false,
    user_vote: null,
  },
];
